name: 💬 RFC
description: 'Request For Comments (RFC) from the community'
title: '💬 RFC: '
labels: [rfc]
body:
  - type: markdown
    attributes:
      value: |
        We value your time and efforts to submit this RFC form. 🙏
  - type: textarea
    id: rfc-need
    validations:
      required: true
    attributes:
      label: '🔖 Need, Context, and Problem Statement'
      description: 'Let us know why are you proposing this change'
      placeholder: 'The problem we’re trying to address and the benefits/impact we expect to get from this are ...'
  - type: textarea
    id: proposal
    validations:
      required: true
    attributes:
      label: '🎉 Proposal'
      description: 'Describe the proposal in as much detail as needed for reviewers to give concrete feedback.'
      placeholder: 'Take special care in this section to describe any implications on data privacy or security.'
  - type: textarea
    id: alternatives
    attributes:
      label: '〽️ Alternatives'
      description: 'What alternatives to the proposed solution were considered?'
      placeholder: 'What criteria/data was used to discard these?'
